from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        title_font = self.titleLabel.font()
        title_font.setPointSize(16)
        title_font.setBold(True)
        self.titleLabel.setFont(title_font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)

        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)

        self.topLayout = QtWidgets.QHBoxLayout()
        self.topLayout.setObjectName("topLayout")

        self.valuesGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.valuesGroupBox.setObjectName("valuesGroupBox")
        self.valuesLayout = QtWidgets.QVBoxLayout(self.valuesGroupBox)
        self.valuesLayout.setObjectName("valuesLayout")

        self.rawGroupBox = QtWidgets.QGroupBox(self.valuesGroupBox)
        self.rawGroupBox.setObjectName("rawGroupBox")
        self.rawFormLayout = QtWidgets.QFormLayout(self.rawGroupBox)
        self.rawFormLayout.setObjectName("rawFormLayout")
        self.rawRollLabel = QtWidgets.QLabel(self.rawGroupBox)
        self.rawRollLabel.setObjectName("rawRollLabel")
        self.rawFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.rawRollLabel)
        self.rawRollValueLabel = QtWidgets.QLabel(self.rawGroupBox)
        self.rawRollValueLabel.setObjectName("rawRollValueLabel")
        self.rawFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rawRollValueLabel)
        self.rawPitchLabel = QtWidgets.QLabel(self.rawGroupBox)
        self.rawPitchLabel.setObjectName("rawPitchLabel")
        self.rawFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.rawPitchLabel)
        self.rawPitchValueLabel = QtWidgets.QLabel(self.rawGroupBox)
        self.rawPitchValueLabel.setObjectName("rawPitchValueLabel")
        self.rawFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.rawPitchValueLabel)
        self.rawYawLabel = QtWidgets.QLabel(self.rawGroupBox)
        self.rawYawLabel.setObjectName("rawYawLabel")
        self.rawFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.rawYawLabel)
        self.rawYawValueLabel = QtWidgets.QLabel(self.rawGroupBox)
        self.rawYawValueLabel.setObjectName("rawYawValueLabel")
        self.rawFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rawYawValueLabel)
        self.valuesLayout.addWidget(self.rawGroupBox)

        self.correctedGroupBox = QtWidgets.QGroupBox(self.valuesGroupBox)
        self.correctedGroupBox.setObjectName("correctedGroupBox")
        self.correctedFormLayout = QtWidgets.QFormLayout(self.correctedGroupBox)
        self.correctedFormLayout.setObjectName("correctedFormLayout")
        self.correctedRollLabel = QtWidgets.QLabel(self.correctedGroupBox)
        self.correctedRollLabel.setObjectName("correctedRollLabel")
        self.correctedFormLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.correctedRollLabel
        )
        self.correctedRollValueLabel = QtWidgets.QLabel(self.correctedGroupBox)
        self.correctedRollValueLabel.setObjectName("correctedRollValueLabel")
        self.correctedFormLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.correctedRollValueLabel
        )
        self.correctedPitchLabel = QtWidgets.QLabel(self.correctedGroupBox)
        self.correctedPitchLabel.setObjectName("correctedPitchLabel")
        self.correctedFormLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.correctedPitchLabel
        )
        self.correctedPitchValueLabel = QtWidgets.QLabel(self.correctedGroupBox)
        self.correctedPitchValueLabel.setObjectName("correctedPitchValueLabel")
        self.correctedFormLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.correctedPitchValueLabel
        )
        self.correctedYawLabel = QtWidgets.QLabel(self.correctedGroupBox)
        self.correctedYawLabel.setObjectName("correctedYawLabel")
        self.correctedFormLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.correctedYawLabel
        )
        self.correctedYawValueLabel = QtWidgets.QLabel(self.correctedGroupBox)
        self.correctedYawValueLabel.setObjectName("correctedYawValueLabel")
        self.correctedFormLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.correctedYawValueLabel
        )
        self.valuesLayout.addWidget(self.correctedGroupBox)

        self.offsetGroupBox = QtWidgets.QGroupBox(self.valuesGroupBox)
        self.offsetGroupBox.setObjectName("offsetGroupBox")
        self.offsetLayout = QtWidgets.QVBoxLayout(self.offsetGroupBox)
        self.offsetLayout.setObjectName("offsetLayout")
        self.offsetValueLabel = QtWidgets.QLabel(self.offsetGroupBox)
        self.offsetValueLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.offsetValueLabel.setObjectName("offsetValueLabel")
        self.offsetLayout.addWidget(self.offsetValueLabel)
        self.valuesLayout.addWidget(self.offsetGroupBox)
        self.valuesLayout.addStretch()
        self.topLayout.addWidget(self.valuesGroupBox, 2)

        self.visualGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.visualGroupBox.setObjectName("visualGroupBox")
        self.visualLayout = QtWidgets.QGridLayout(self.visualGroupBox)
        self.visualLayout.setObjectName("visualLayout")

        self.yawDialTitleLabel = QtWidgets.QLabel(self.visualGroupBox)
        self.yawDialTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.yawDialTitleLabel.setObjectName("yawDialTitleLabel")
        self.visualLayout.addWidget(self.yawDialTitleLabel, 0, 0, 1, 1)
        self.pitchSliderTitleLabel = QtWidgets.QLabel(self.visualGroupBox)
        self.pitchSliderTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pitchSliderTitleLabel.setObjectName("pitchSliderTitleLabel")
        self.visualLayout.addWidget(self.pitchSliderTitleLabel, 0, 1, 1, 1)

        self.yawDial = QtWidgets.QDial(self.visualGroupBox)
        self.yawDial.setMinimumSize(QtCore.QSize(260, 260))
        self.yawDial.setObjectName("yawDial")
        self.visualLayout.addWidget(self.yawDial, 1, 0, 2, 1)

        self.pitchSlider = QtWidgets.QSlider(self.visualGroupBox)
        self.pitchSlider.setMinimumSize(QtCore.QSize(60, 260))
        self.pitchSlider.setOrientation(QtCore.Qt.Vertical)
        self.pitchSlider.setObjectName("pitchSlider")
        self.visualLayout.addWidget(self.pitchSlider, 1, 1, 2, 1)

        self.rollSliderTitleLabel = QtWidgets.QLabel(self.visualGroupBox)
        self.rollSliderTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rollSliderTitleLabel.setObjectName("rollSliderTitleLabel")
        self.visualLayout.addWidget(self.rollSliderTitleLabel, 3, 0, 1, 2)

        self.rollSlider = QtWidgets.QSlider(self.visualGroupBox)
        self.rollSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rollSlider.setObjectName("rollSlider")
        self.visualLayout.addWidget(self.rollSlider, 4, 0, 1, 2)

        self.topLayout.addWidget(self.visualGroupBox, 3)
        self.verticalLayout.addLayout(self.topLayout)

        self.buttonGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.buttonGroupBox.setObjectName("buttonGroupBox")
        self.buttonLayout = QtWidgets.QGridLayout(self.buttonGroupBox)
        self.buttonLayout.setObjectName("buttonLayout")
        self.setYaw0Button = QtWidgets.QPushButton(self.buttonGroupBox)
        self.setYaw0Button.setObjectName("setYaw0Button")
        self.buttonLayout.addWidget(self.setYaw0Button, 0, 0, 1, 1)
        self.setYaw180Button = QtWidgets.QPushButton(self.buttonGroupBox)
        self.setYaw180Button.setObjectName("setYaw180Button")
        self.buttonLayout.addWidget(self.setYaw180Button, 0, 1, 1, 1)
        self.setYaw90Button = QtWidgets.QPushButton(self.buttonGroupBox)
        self.setYaw90Button.setObjectName("setYaw90Button")
        self.buttonLayout.addWidget(self.setYaw90Button, 0, 2, 1, 1)
        self.setYawNeg90Button = QtWidgets.QPushButton(self.buttonGroupBox)
        self.setYawNeg90Button.setObjectName("setYawNeg90Button")
        self.buttonLayout.addWidget(self.setYawNeg90Button, 0, 3, 1, 1)
        self.setRollButton = QtWidgets.QPushButton(self.buttonGroupBox)
        self.setRollButton.setObjectName("setRollButton")
        self.buttonLayout.addWidget(self.setRollButton, 1, 0, 1, 2)
        self.setPitchButton = QtWidgets.QPushButton(self.buttonGroupBox)
        self.setPitchButton.setObjectName("setPitchButton")
        self.buttonLayout.addWidget(self.setPitchButton, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.buttonGroupBox)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "client_imu"))
        self.titleLabel.setText(_translate("MainWindow", "client_imu IMU Monitor"))
        self.statusLabel.setText(_translate("MainWindow", "No IMU data"))
        self.valuesGroupBox.setTitle(_translate("MainWindow", "Values"))
        self.rawGroupBox.setTitle(_translate("MainWindow", "Raw RPY"))
        self.rawRollLabel.setText(_translate("MainWindow", "Roll"))
        self.rawRollValueLabel.setText(_translate("MainWindow", "No IMU data"))
        self.rawPitchLabel.setText(_translate("MainWindow", "Pitch"))
        self.rawPitchValueLabel.setText(_translate("MainWindow", "No IMU data"))
        self.rawYawLabel.setText(_translate("MainWindow", "Yaw"))
        self.rawYawValueLabel.setText(_translate("MainWindow", "No IMU data"))
        self.correctedGroupBox.setTitle(_translate("MainWindow", "Corrected RPY"))
        self.correctedRollLabel.setText(_translate("MainWindow", "Roll"))
        self.correctedRollValueLabel.setText(_translate("MainWindow", "No IMU data"))
        self.correctedPitchLabel.setText(_translate("MainWindow", "Pitch"))
        self.correctedPitchValueLabel.setText(_translate("MainWindow", "No IMU data"))
        self.correctedYawLabel.setText(_translate("MainWindow", "Yaw"))
        self.correctedYawValueLabel.setText(_translate("MainWindow", "No IMU data"))
        self.offsetGroupBox.setTitle(_translate("MainWindow", "Offsets"))
        self.offsetValueLabel.setText(
            _translate("MainWindow", "Roll 0.0 / Pitch 0.0 / Yaw 0.0")
        )
        self.visualGroupBox.setTitle(_translate("MainWindow", "Attitude View"))
        self.yawDialTitleLabel.setText(_translate("MainWindow", "Yaw"))
        self.pitchSliderTitleLabel.setText(_translate("MainWindow", "Pitch"))
        self.rollSliderTitleLabel.setText(_translate("MainWindow", "Roll"))
        self.buttonGroupBox.setTitle(_translate("MainWindow", "Controls"))
        self.setYaw0Button.setText(_translate("MainWindow", "Set Yaw 0"))
        self.setYaw180Button.setText(_translate("MainWindow", "Set Yaw 180"))
        self.setYaw90Button.setText(_translate("MainWindow", "Set Yaw 90"))
        self.setYawNeg90Button.setText(_translate("MainWindow", "Set Yaw -90"))
        self.setRollButton.setText(_translate("MainWindow", "Set Roll"))
        self.setPitchButton.setText(_translate("MainWindow", "Set Pitch"))
